// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1:string,arg2:number):Promise<void>;

export function DisconnectSerial():Promise<void>;

export function ListSerialPorts():Promise<Array<string>>;
