// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartMavlink(arg1) {
  return window['go']['main']['App']['StartMavlink'](arg1);
}

export function StopMavlink() {
  return window['go']['main']['App']['StopMavlink']();
}
