// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortRocket():Promise<void>;

export function ArmRocket():Promise<void>;

export function DisarmRocket():Promise<void>;

export function LaunchRocket():Promise<void>;

export function StartMavlink(arg1:string):Promise<void>;

export function StopMavlink():Promise<void>;
