// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSerial(arg1, arg2) {
  return window['go']['main']['App']['ConnectSerial'](arg1, arg2);
}

export function DisconnectSerial() {
  return window['go']['main']['App']['DisconnectSerial']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function OpenLogFile() {
  return window['go']['main']['App']['OpenLogFile']();
}

export function SaveFlightLog(arg1) {
  return window['go']['main']['App']['SaveFlightLog'](arg1);
}
