// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AbortRocket() {
  return window['go']['main']['App']['AbortRocket']();
}

export function ArmRocket() {
  return window['go']['main']['App']['ArmRocket']();
}

export function DisarmRocket() {
  return window['go']['main']['App']['DisarmRocket']();
}

export function LaunchRocket() {
  return window['go']['main']['App']['LaunchRocket']();
}

export function StartMavlink(arg1) {
  return window['go']['main']['App']['StartMavlink'](arg1);
}

export function StopMavlink() {
  return window['go']['main']['App']['StopMavlink']();
}
