// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartMavlink(arg1:number):Promise<void>;

export function StopMavlink():Promise<void>;
